/**
 * generated by Xtext 2.23.0
 */
package org.xtext.enigme.eNIGME.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.xtext.enigme.eNIGME.util.ENIGMEAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ENIGMEItemProviderAdapterFactory extends ENIGMEAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ENIGMEItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Jeu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JeuItemProvider jeuItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Jeu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJeuAdapter() {
		if (jeuItemProvider == null) {
			jeuItemProvider = new JeuItemProvider(this);
		}

		return jeuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Joueur} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoueurItemProvider joueurItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Joueur}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoueurAdapter() {
		if (joueurItemProvider == null) {
			joueurItemProvider = new JoueurItemProvider(this);
		}

		return joueurItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Objet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjetItemProvider objetItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Objet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjetAdapter() {
		if (objetItemProvider == null) {
			objetItemProvider = new ObjetItemProvider(this);
		}

		return objetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Territoire} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TerritoireItemProvider territoireItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Territoire}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTerritoireAdapter() {
		if (territoireItemProvider == null) {
			territoireItemProvider = new TerritoireItemProvider(this);
		}

		return territoireItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Choix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoixItemProvider choixItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Choix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoixAdapter() {
		if (choixItemProvider == null) {
			choixItemProvider = new ChoixItemProvider(this);
		}

		return choixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Interaction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InteractionItemProvider interactionItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Interaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInteractionAdapter() {
		if (interactionItemProvider == null) {
			interactionItemProvider = new InteractionItemProvider(this);
		}

		return interactionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Personne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersonneItemProvider personneItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Personne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersonneAdapter() {
		if (personneItemProvider == null) {
			personneItemProvider = new PersonneItemProvider(this);
		}

		return personneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Lieu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LieuItemProvider lieuItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Lieu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLieuAdapter() {
		if (lieuItemProvider == null) {
			lieuItemProvider = new LieuItemProvider(this);
		}

		return lieuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Chemin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CheminItemProvider cheminItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Chemin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCheminAdapter() {
		if (cheminItemProvider == null) {
			cheminItemProvider = new CheminItemProvider(this);
		}

		return cheminItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Qualification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QualificationItemProvider qualificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Qualification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQualificationAdapter() {
		if (qualificationItemProvider == null) {
			qualificationItemProvider = new QualificationItemProvider(this);
		}

		return qualificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionItemProvider actionItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionAdapter() {
		if (actionItemProvider == null) {
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.xtext.enigme.eNIGME.Reponse} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReponseItemProvider reponseItemProvider;

	/**
	 * This creates an adapter for a {@link org.xtext.enigme.eNIGME.Reponse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReponseAdapter() {
		if (reponseItemProvider == null) {
			reponseItemProvider = new ReponseItemProvider(this);
		}

		return reponseItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (jeuItemProvider != null) jeuItemProvider.dispose();
		if (joueurItemProvider != null) joueurItemProvider.dispose();
		if (objetItemProvider != null) objetItemProvider.dispose();
		if (territoireItemProvider != null) territoireItemProvider.dispose();
		if (choixItemProvider != null) choixItemProvider.dispose();
		if (interactionItemProvider != null) interactionItemProvider.dispose();
		if (personneItemProvider != null) personneItemProvider.dispose();
		if (lieuItemProvider != null) lieuItemProvider.dispose();
		if (cheminItemProvider != null) cheminItemProvider.dispose();
		if (qualificationItemProvider != null) qualificationItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
		if (reponseItemProvider != null) reponseItemProvider.dispose();
	}

}
