/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGME;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jeu Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.eNIGME.ENIGMEPackage#getJeuElement()
 * @model
 * @generated
 */
public interface JeuElement extends EObject
{
} // JeuElement
