/*
 * generated by Xtext 2.23.0
 */
package org.xtext.enigme;

import fr.n7.ENIGMEStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ENIGMEStandaloneSetup extends ENIGMEStandaloneSetupGenerated {

	public static void doSetup() {
		new ENIGMEStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
