/*
 * generated by Xtext 2.23.0
 */
package org.xtext.enigme.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.enigme.ENIGMERuntimeModule;
import org.xtext.enigme.ENIGMEStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ENIGMEIdeSetup extends ENIGMEStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ENIGMERuntimeModule(), new ENIGMEIdeModule()));
	}
	
}
