/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.xtext.game.ui.internal.GameActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GAMEUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameActivator.getInstance().getInjector("fr.n7.GAME");
	}

}
