/**
 * generated by Xtext 2.23.0
 */
package fr.n7.gAME.impl;

import fr.n7.gAME.Chemin;
import fr.n7.gAME.Connaissance;
import fr.n7.gAME.GAMEPackage;
import fr.n7.gAME.Lieu;
import fr.n7.gAME.Objet;
import fr.n7.gAME.Personne;
import fr.n7.gAME.Qualification;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gAME.impl.LieuImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.gAME.impl.LieuImpl#getPersonnes <em>Personnes</em>}</li>
 *   <li>{@link fr.n7.gAME.impl.LieuImpl#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.n7.gAME.impl.LieuImpl#getConnaisances <em>Connaisances</em>}</li>
 *   <li>{@link fr.n7.gAME.impl.LieuImpl#getChemin <em>Chemin</em>}</li>
 *   <li>{@link fr.n7.gAME.impl.LieuImpl#getQualification <em>Qualification</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LieuImpl extends MinimalEObjectImpl.Container implements Lieu
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPersonnes() <em>Personnes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersonnes()
   * @generated
   * @ordered
   */
  protected EList<Personne> personnes;

  /**
   * The cached value of the '{@link #getObjets() <em>Objets</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjets()
   * @generated
   * @ordered
   */
  protected EList<Objet> objets;

  /**
   * The cached value of the '{@link #getConnaisances() <em>Connaisances</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnaisances()
   * @generated
   * @ordered
   */
  protected EList<Connaissance> connaisances;

  /**
   * The cached value of the '{@link #getChemin() <em>Chemin</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChemin()
   * @generated
   * @ordered
   */
  protected EList<Chemin> chemin;

  /**
   * The cached value of the '{@link #getQualification() <em>Qualification</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQualification()
   * @generated
   * @ordered
   */
  protected EList<Qualification> qualification;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LieuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GAMEPackage.Literals.LIEU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GAMEPackage.LIEU__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Personne> getPersonnes()
  {
    if (personnes == null)
    {
      personnes = new EObjectContainmentEList<Personne>(Personne.class, this, GAMEPackage.LIEU__PERSONNES);
    }
    return personnes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Objet> getObjets()
  {
    if (objets == null)
    {
      objets = new EObjectContainmentEList<Objet>(Objet.class, this, GAMEPackage.LIEU__OBJETS);
    }
    return objets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Connaissance> getConnaisances()
  {
    if (connaisances == null)
    {
      connaisances = new EObjectContainmentEList<Connaissance>(Connaissance.class, this, GAMEPackage.LIEU__CONNAISANCES);
    }
    return connaisances;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Chemin> getChemin()
  {
    if (chemin == null)
    {
      chemin = new EObjectContainmentEList<Chemin>(Chemin.class, this, GAMEPackage.LIEU__CHEMIN);
    }
    return chemin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Qualification> getQualification()
  {
    if (qualification == null)
    {
      qualification = new EObjectContainmentEList<Qualification>(Qualification.class, this, GAMEPackage.LIEU__QUALIFICATION);
    }
    return qualification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GAMEPackage.LIEU__PERSONNES:
        return ((InternalEList<?>)getPersonnes()).basicRemove(otherEnd, msgs);
      case GAMEPackage.LIEU__OBJETS:
        return ((InternalEList<?>)getObjets()).basicRemove(otherEnd, msgs);
      case GAMEPackage.LIEU__CONNAISANCES:
        return ((InternalEList<?>)getConnaisances()).basicRemove(otherEnd, msgs);
      case GAMEPackage.LIEU__CHEMIN:
        return ((InternalEList<?>)getChemin()).basicRemove(otherEnd, msgs);
      case GAMEPackage.LIEU__QUALIFICATION:
        return ((InternalEList<?>)getQualification()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GAMEPackage.LIEU__NAME:
        return getName();
      case GAMEPackage.LIEU__PERSONNES:
        return getPersonnes();
      case GAMEPackage.LIEU__OBJETS:
        return getObjets();
      case GAMEPackage.LIEU__CONNAISANCES:
        return getConnaisances();
      case GAMEPackage.LIEU__CHEMIN:
        return getChemin();
      case GAMEPackage.LIEU__QUALIFICATION:
        return getQualification();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GAMEPackage.LIEU__NAME:
        setName((String)newValue);
        return;
      case GAMEPackage.LIEU__PERSONNES:
        getPersonnes().clear();
        getPersonnes().addAll((Collection<? extends Personne>)newValue);
        return;
      case GAMEPackage.LIEU__OBJETS:
        getObjets().clear();
        getObjets().addAll((Collection<? extends Objet>)newValue);
        return;
      case GAMEPackage.LIEU__CONNAISANCES:
        getConnaisances().clear();
        getConnaisances().addAll((Collection<? extends Connaissance>)newValue);
        return;
      case GAMEPackage.LIEU__CHEMIN:
        getChemin().clear();
        getChemin().addAll((Collection<? extends Chemin>)newValue);
        return;
      case GAMEPackage.LIEU__QUALIFICATION:
        getQualification().clear();
        getQualification().addAll((Collection<? extends Qualification>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GAMEPackage.LIEU__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GAMEPackage.LIEU__PERSONNES:
        getPersonnes().clear();
        return;
      case GAMEPackage.LIEU__OBJETS:
        getObjets().clear();
        return;
      case GAMEPackage.LIEU__CONNAISANCES:
        getConnaisances().clear();
        return;
      case GAMEPackage.LIEU__CHEMIN:
        getChemin().clear();
        return;
      case GAMEPackage.LIEU__QUALIFICATION:
        getQualification().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GAMEPackage.LIEU__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GAMEPackage.LIEU__PERSONNES:
        return personnes != null && !personnes.isEmpty();
      case GAMEPackage.LIEU__OBJETS:
        return objets != null && !objets.isEmpty();
      case GAMEPackage.LIEU__CONNAISANCES:
        return connaisances != null && !connaisances.isEmpty();
      case GAMEPackage.LIEU__CHEMIN:
        return chemin != null && !chemin.isEmpty();
      case GAMEPackage.LIEU__QUALIFICATION:
        return qualification != null && !qualification.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //LieuImpl
