/**
 * generated by Xtext 2.23.0
 */
package fr.n7.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gAME.Action#getObjetsConsommes <em>Objets Consommes</em>}</li>
 *   <li>{@link fr.n7.gAME.Action#getObjetsProduits <em>Objets Produits</em>}</li>
 *   <li>{@link fr.n7.gAME.Action#getConnaissanceProduits <em>Connaissance Produits</em>}</li>
 *   <li>{@link fr.n7.gAME.Action#getQualification <em>Qualification</em>}</li>
 * </ul>
 *
 * @see fr.n7.gAME.GAMEPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Objets Consommes</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets Consommes</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getAction_ObjetsConsommes()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjetsConsommes();

  /**
   * Returns the value of the '<em><b>Objets Produits</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets Produits</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getAction_ObjetsProduits()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjetsProduits();

  /**
   * Returns the value of the '<em><b>Connaissance Produits</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissance Produits</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getAction_ConnaissanceProduits()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getConnaissanceProduits();

  /**
   * Returns the value of the '<em><b>Qualification</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Qualification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualification</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getAction_Qualification()
   * @model containment="true"
   * @generated
   */
  EList<Qualification> getQualification();

} // Action
