/**
 * generated by Xtext 2.23.0
 */
package fr.n7.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chemin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gAME.Chemin#getEtat <em>Etat</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getSuccessor <em>Successor</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getConditionsVisible <em>Conditions Visible</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getConditionsOuverture <em>Conditions Ouverture</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getConditionsObligation <em>Conditions Obligation</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getObjetsTransmis <em>Objets Transmis</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getPrixObjets <em>Prix Objets</em>}</li>
 *   <li>{@link fr.n7.gAME.Chemin#getQualification <em>Qualification</em>}</li>
 * </ul>
 *
 * @see fr.n7.gAME.GAMEPackage#getChemin()
 * @model
 * @generated
 */
public interface Chemin extends EObject
{
  /**
   * Returns the value of the '<em><b>Etat</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.gAME.EtatChemin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etat</em>' attribute.
   * @see fr.n7.gAME.EtatChemin
   * @see #setEtat(EtatChemin)
   * @see fr.n7.gAME.GAMEPackage#getChemin_Etat()
   * @model
   * @generated
   */
  EtatChemin getEtat();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Chemin#getEtat <em>Etat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etat</em>' attribute.
   * @see fr.n7.gAME.EtatChemin
   * @see #getEtat()
   * @generated
   */
  void setEtat(EtatChemin value);

  /**
   * Returns the value of the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predecessor</em>' reference.
   * @see #setPredecessor(Lieu)
   * @see fr.n7.gAME.GAMEPackage#getChemin_Predecessor()
   * @model
   * @generated
   */
  Lieu getPredecessor();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Chemin#getPredecessor <em>Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predecessor</em>' reference.
   * @see #getPredecessor()
   * @generated
   */
  void setPredecessor(Lieu value);

  /**
   * Returns the value of the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Successor</em>' reference.
   * @see #setSuccessor(Lieu)
   * @see fr.n7.gAME.GAMEPackage#getChemin_Successor()
   * @model
   * @generated
   */
  Lieu getSuccessor();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Chemin#getSuccessor <em>Successor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Successor</em>' reference.
   * @see #getSuccessor()
   * @generated
   */
  void setSuccessor(Lieu value);

  /**
   * Returns the value of the '<em><b>Conditions Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Visible</em>' containment reference.
   * @see #setConditionsVisible(Condition)
   * @see fr.n7.gAME.GAMEPackage#getChemin_ConditionsVisible()
   * @model containment="true"
   * @generated
   */
  Condition getConditionsVisible();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Chemin#getConditionsVisible <em>Conditions Visible</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions Visible</em>' containment reference.
   * @see #getConditionsVisible()
   * @generated
   */
  void setConditionsVisible(Condition value);

  /**
   * Returns the value of the '<em><b>Conditions Ouverture</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Ouverture</em>' containment reference.
   * @see #setConditionsOuverture(Condition)
   * @see fr.n7.gAME.GAMEPackage#getChemin_ConditionsOuverture()
   * @model containment="true"
   * @generated
   */
  Condition getConditionsOuverture();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Chemin#getConditionsOuverture <em>Conditions Ouverture</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions Ouverture</em>' containment reference.
   * @see #getConditionsOuverture()
   * @generated
   */
  void setConditionsOuverture(Condition value);

  /**
   * Returns the value of the '<em><b>Conditions Obligation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Obligation</em>' containment reference.
   * @see #setConditionsObligation(Condition)
   * @see fr.n7.gAME.GAMEPackage#getChemin_ConditionsObligation()
   * @model containment="true"
   * @generated
   */
  Condition getConditionsObligation();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Chemin#getConditionsObligation <em>Conditions Obligation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions Obligation</em>' containment reference.
   * @see #getConditionsObligation()
   * @generated
   */
  void setConditionsObligation(Condition value);

  /**
   * Returns the value of the '<em><b>Objets Transmis</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets Transmis</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getChemin_ObjetsTransmis()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjetsTransmis();

  /**
   * Returns the value of the '<em><b>Prix Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prix Objets</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getChemin_PrixObjets()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getPrixObjets();

  /**
   * Returns the value of the '<em><b>Qualification</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Qualification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualification</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getChemin_Qualification()
   * @model containment="true"
   * @generated
   */
  EList<Qualification> getQualification();

} // Chemin
