/**
 * generated by Xtext 2.23.0
 */
package fr.n7.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Explorateur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gAME.Explorateur#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.gAME.Explorateur#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.n7.gAME.Explorateur#getConnaissances <em>Connaissances</em>}</li>
 *   <li>{@link fr.n7.gAME.Explorateur#getLieuCourant <em>Lieu Courant</em>}</li>
 *   <li>{@link fr.n7.gAME.Explorateur#getLieuExplores <em>Lieu Explores</em>}</li>
 *   <li>{@link fr.n7.gAME.Explorateur#getLimite <em>Limite</em>}</li>
 * </ul>
 *
 * @see fr.n7.gAME.GAMEPackage#getExplorateur()
 * @model
 * @generated
 */
public interface Explorateur extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.gAME.GAMEPackage#getExplorateur_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Explorateur#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getExplorateur_Objets()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getObjets();

  /**
   * Returns the value of the '<em><b>Connaissances</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getExplorateur_Connaissances()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getConnaissances();

  /**
   * Returns the value of the '<em><b>Lieu Courant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieu Courant</em>' reference.
   * @see #setLieuCourant(Lieu)
   * @see fr.n7.gAME.GAMEPackage#getExplorateur_LieuCourant()
   * @model
   * @generated
   */
  Lieu getLieuCourant();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Explorateur#getLieuCourant <em>Lieu Courant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lieu Courant</em>' reference.
   * @see #getLieuCourant()
   * @generated
   */
  void setLieuCourant(Lieu value);

  /**
   * Returns the value of the '<em><b>Lieu Explores</b></em>' reference list.
   * The list contents are of type {@link fr.n7.gAME.Lieu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieu Explores</em>' reference list.
   * @see fr.n7.gAME.GAMEPackage#getExplorateur_LieuExplores()
   * @model
   * @generated
   */
  EList<Lieu> getLieuExplores();

  /**
   * Returns the value of the '<em><b>Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Limite</em>' attribute.
   * @see #setLimite(int)
   * @see fr.n7.gAME.GAMEPackage#getExplorateur_Limite()
   * @model
   * @generated
   */
  int getLimite();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Explorateur#getLimite <em>Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Limite</em>' attribute.
   * @see #getLimite()
   * @generated
   */
  void setLimite(int value);

} // Explorateur
