/**
 * generated by Xtext 2.23.0
 */
package fr.n7.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gAME.Interaction#getChoixDebut <em>Choix Debut</em>}</li>
 *   <li>{@link fr.n7.gAME.Interaction#getChoixInter <em>Choix Inter</em>}</li>
 *   <li>{@link fr.n7.gAME.Interaction#getChoixFin <em>Choix Fin</em>}</li>
 *   <li>{@link fr.n7.gAME.Interaction#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see fr.n7.gAME.GAMEPackage#getInteraction()
 * @model
 * @generated
 */
public interface Interaction extends EObject
{
  /**
   * Returns the value of the '<em><b>Choix Debut</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix Debut</em>' containment reference.
   * @see #setChoixDebut(Choix)
   * @see fr.n7.gAME.GAMEPackage#getInteraction_ChoixDebut()
   * @model containment="true"
   * @generated
   */
  Choix getChoixDebut();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Interaction#getChoixDebut <em>Choix Debut</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choix Debut</em>' containment reference.
   * @see #getChoixDebut()
   * @generated
   */
  void setChoixDebut(Choix value);

  /**
   * Returns the value of the '<em><b>Choix Inter</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Choix}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix Inter</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getInteraction_ChoixInter()
   * @model containment="true"
   * @generated
   */
  EList<Choix> getChoixInter();

  /**
   * Returns the value of the '<em><b>Choix Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix Fin</em>' containment reference.
   * @see #setChoixFin(Choix)
   * @see fr.n7.gAME.GAMEPackage#getInteraction_ChoixFin()
   * @model containment="true"
   * @generated
   */
  Choix getChoixFin();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Interaction#getChoixFin <em>Choix Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choix Fin</em>' containment reference.
   * @see #getChoixFin()
   * @generated
   */
  void setChoixFin(Choix value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see fr.n7.gAME.GAMEPackage#getInteraction_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Interaction#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

} // Interaction
