/**
 * generated by Xtext 2.23.0
 */
package fr.n7.gAME;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Personne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gAME.Personne#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.gAME.Personne#getActivite <em>Activite</em>}</li>
 *   <li>{@link fr.n7.gAME.Personne#getConditionsVisible <em>Conditions Visible</em>}</li>
 *   <li>{@link fr.n7.gAME.Personne#getConditionsObligation <em>Conditions Obligation</em>}</li>
 *   <li>{@link fr.n7.gAME.Personne#getInteraction <em>Interaction</em>}</li>
 *   <li>{@link fr.n7.gAME.Personne#getQualification <em>Qualification</em>}</li>
 * </ul>
 *
 * @see fr.n7.gAME.GAMEPackage#getPersonne()
 * @model
 * @generated
 */
public interface Personne extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.gAME.GAMEPackage#getPersonne_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Personne#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Activite</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.gAME.Activite}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activite</em>' attribute.
   * @see fr.n7.gAME.Activite
   * @see #setActivite(Activite)
   * @see fr.n7.gAME.GAMEPackage#getPersonne_Activite()
   * @model
   * @generated
   */
  Activite getActivite();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Personne#getActivite <em>Activite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activite</em>' attribute.
   * @see fr.n7.gAME.Activite
   * @see #getActivite()
   * @generated
   */
  void setActivite(Activite value);

  /**
   * Returns the value of the '<em><b>Conditions Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Visible</em>' containment reference.
   * @see #setConditionsVisible(Condition)
   * @see fr.n7.gAME.GAMEPackage#getPersonne_ConditionsVisible()
   * @model containment="true"
   * @generated
   */
  Condition getConditionsVisible();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Personne#getConditionsVisible <em>Conditions Visible</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions Visible</em>' containment reference.
   * @see #getConditionsVisible()
   * @generated
   */
  void setConditionsVisible(Condition value);

  /**
   * Returns the value of the '<em><b>Conditions Obligation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Obligation</em>' containment reference.
   * @see #setConditionsObligation(Condition)
   * @see fr.n7.gAME.GAMEPackage#getPersonne_ConditionsObligation()
   * @model containment="true"
   * @generated
   */
  Condition getConditionsObligation();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Personne#getConditionsObligation <em>Conditions Obligation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditions Obligation</em>' containment reference.
   * @see #getConditionsObligation()
   * @generated
   */
  void setConditionsObligation(Condition value);

  /**
   * Returns the value of the '<em><b>Interaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interaction</em>' containment reference.
   * @see #setInteraction(Interaction)
   * @see fr.n7.gAME.GAMEPackage#getPersonne_Interaction()
   * @model containment="true"
   * @generated
   */
  Interaction getInteraction();

  /**
   * Sets the value of the '{@link fr.n7.gAME.Personne#getInteraction <em>Interaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interaction</em>' containment reference.
   * @see #getInteraction()
   * @generated
   */
  void setInteraction(Interaction value);

  /**
   * Returns the value of the '<em><b>Qualification</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gAME.Qualification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualification</em>' containment reference list.
   * @see fr.n7.gAME.GAMEPackage#getPersonne_Qualification()
   * @model containment="true"
   * @generated
   */
  EList<Qualification> getQualification();

} // Personne
