/**
 * generated by Xtext 2.23.0
 */
package fr.n7.eNIGME.tests;

import fr.n7.eNIGME.ENIGMEFactory;
import fr.n7.eNIGME.Territoire;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Territoire</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class TerritoireTest extends JeuElementTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(TerritoireTest.class);
	}

	/**
	 * Constructs a new Territoire test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TerritoireTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Territoire test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Territoire getFixture() {
		return (Territoire)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ENIGMEFactory.eINSTANCE.createTerritoire());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //TerritoireTest
