/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.xtext.game.ui.internal.GameActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GAMEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GameActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GameActivator activator = GameActivator.getInstance();
		return activator != null ? activator.getInjector(GameActivator.FR_N7_GAME) : null;
	}

}
