/**
 * generated by Xtext 2.23.0
 */
package org.xtext.enigme.eNIGME.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.enigme.eNIGME.Chemin;
import org.xtext.enigme.eNIGME.ENIGMEFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Chemin</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class CheminTest extends TestCase {

	/**
	 * The fixture for this Chemin test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Chemin fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(CheminTest.class);
	}

	/**
	 * Constructs a new Chemin test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CheminTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Chemin test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Chemin fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Chemin test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Chemin getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ENIGMEFactory.eINSTANCE.createChemin());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //CheminTest
