/*
 * generated by Xtext 2.23.0
 */
package org.xtext.enigme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import fr.n7.ui.AbstractENIGMEUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ENIGMEUiModule extends AbstractENIGMEUiModule {

	public ENIGMEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
