/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.enigme.ui.internal.EnigmeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ENIGMEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EnigmeActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EnigmeActivator activator = EnigmeActivator.getInstance();
		return activator != null ? activator.getInjector(EnigmeActivator.FR_N7_ENIGME) : null;
	}

}
